updated docs for installation instructions
rinikerlab/customETKDG pull request #2
Opened 2022-02-06 18:38 UTC by hjuinj

2022-02-07 05:12 UTC, greglandrum requested changes
There are a few things that I think should be changed

2022-02-07 05:12 UTC, greglandrum commented on README.md
> +git clone -b api --single-branch https://github.com/rinikerlab/customETKDG.git
Do you really want them to clone this specific branch? Wouldn't "master" be better?

2022-02-07 05:12 UTC, greglandrum commented on environment.yml
> +  - rdkit
What is the rdkit channel being used for? we don't keep those packages up to date any more

2022-02-07 05:12 UTC, greglandrum commented on environment.yml
> +  - anyio=3.3.4=py37hf985489_0
This level of detail (including version and build number) will only work on linux. I don't think that's what you intend?

2022-02-07 05:12 UTC, greglandrum commented on README.md
> +## Installation
You might also want to mention pip's "install directly from github repo" feature. This is a lot easier for people who aren't doing development work:
```
pip install git+https://github.com/rinikerlab/customETKDG
```

2022-02-07 05:12 UTC, greglandrum commented on README.md
> +@article{wang2022incorporating,
please include the DOI link

2022-02-07 21:44 UTC, hjuinj commented on README.md
> +git clone -b api --single-branch https://github.com/rinikerlab/customETKDG.git
actually at the moment `api` is the main branch, how should we best change this?
The reason I only want people to clone a single branch is because when Kajo was developing the code he accidentally pushed some data files which are a bit large.

2022-02-07 21:47 UTC, hjuinj commented on environment.yml
> +  - anyio=3.3.4=py37hf985489_0
what I found was that when I was creating an environment from the previous version of the yml file (with no versioning)  it was stuck on resolving the dependencies forever, basically halted. 

So I exported the conda environment that I used when developing this package into a yml file and when I tried to create environment using that (on mac) it worked nicely.

2022-02-07 21:47 UTC, hjuinj commented on environment.yml
> +  - rdkit
I can remove that, this was auto-generated.

2022-02-07 21:50 UTC, hjuinj commented on README.md
> +## Installation
would it work without the user first installing all the dependencies in `environment.yml`? I guess it would be: user first download the yml file, create environment, then do the pip install git+ right?

2022-02-11 12:48 UTC, greglandrum commented on README.md
> +git clone -b api --single-branch https://github.com/rinikerlab/customETKDG.git
Unless you have an argument for doing it some other way: I'd rather that we have master (or main, whatever we want to call it) be the primary branch and then do development on other branches which get merged back into that.

2022-02-11 12:49 UTC, greglandrum commented on environment.yml
> +  - rdkit
yeah, please do... if someone accidentally ends up with one of those versions of the RDKit then they are stuck with something very old

2022-02-11 12:51 UTC, greglandrum commented on environment.yml
> +  - anyio=3.3.4=py37hf985489_0
So you created the .yml file on a Mac?

2022-02-11 12:53 UTC, greglandrum commented on README.md
> +## Installation
right... when using a mix of conda and pip, you always have to manually install the other one.

2022-02-11 12:56 UTC, greglandrum commented on environment.yml
> +  - anyio=3.3.4=py37hf985489_0
> what I found was that when I was creating an environment from the previous version of the yml file (with no versioning) it was stuck on resolving the dependencies forever, basically halted.

And, to be clear, I was not suggesting .yml file without versions. I was suggesting a yml file without BUILD ids. You can get this with `conda env export --from-history`. More information here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-an-environment-file-across-platforms

2022-02-11 16:49 UTC, greglandrum approved these changes

2022-02-11 16:49 UTC, merged